var num1 = 10;
var num2 = 5;
var str1 = "Hello";
var str2 = "World";
var bool1 = true;
var bool2 = false;
var undef = undefined;
console.log("Number Operations:");
console.log("num1 + num2:", num1 + num2);
console.log("num1 - num2:", num1 - num2);
console.log("num1 * num2:", num1 * num2);
console.log("num1 / num2:", num1 / num2);
console.log();
console.log("String Operations:");
console.log("str1 + str2:", str1 + " " + str2);
console.log();
console.log("Boolean Operations:");
console.log("bool1 && bool2:", bool1 && bool2);
console.log("bool1 || bool2:", bool1 || bool2);
console.log("!bool1:", !bool1);
console.log();
console.log("Undefined Operation:");
console.log("Value of undefined variable:", undef);
